version: '3.7'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: password
    networks:
      - main
    ports:
      - '$HOST_DB_PORT:3306'
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
  
  api:
    depends_on:
      - db
    build:
      context: .
    env_file: .env
    networks:
      - main
    ports:
      - '$HOST_API_PORT:8000'
    command: sh -c "./wait-for db:${DB_PORT} && ./app"

networks:
  main:
